# Generated by Django 4.0 on 2024-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('wallet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('petrol_purchased', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diesel_purchased', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_petrol_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_diesel_rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
