# Generated by Django 4.0 on 2024-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('dispenser_id', models.IntegerField(primary_key=True, serialize=False)),
                ('petrol_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diesel_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('petrol_stock', models.IntegerField()),
                ('diesel_stock', models.IntegerField()),
            ],
        ),
    ]
