# Generated by Django 4.0 on 2024-04-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispenser',
            name='dispensing_mode',
            field=models.BooleanField(default=False),
        ),
    ]
