# Generated by Django 4.0 on 2024-05-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petrol', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
